apiVersion: v2
name: authorization-service
description: Stateless role/route authorization decision service (NestJS)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: sa-common
    version: 0.1.0
    repository: "file://../sa-common"
