apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ required "rabbitmq: auth.username es obligatorio" .Values.auth.username | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ required "rabbitmq: auth.password es obligatorio (ver values.example.yaml)" .Values.auth.password | b64enc | quote }}
