apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
automountServiceAccountToken: false
