apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-headless
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
